name: release

on: workflow_dispatch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine next version
        id: semver
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          NONE_STRING_TOKEN: (none)
          PATCH_STRING_TOKEN: (patch)
          MINOR_STRING_TOKEN: (minor)
          MAJOR_STRING_TOKEN: (major)
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.tag }}
          release_name: Release ${{ steps.semver.outputs.tag }}
          body: ${{steps.changelog.outputs.changelog}}
